### ISSUE TITLE
Explore the Java 8 modules if we can make the container image even smaller

### ISSUE THREAD

**Issue by Jiri-Kremser** [Jiri-Kremser/spark-operator#9]
..by disabling unused modules, like xml processing, corba perhaps, etc.

**Comment by Jiri-Kremser** [comment]
also related https://www.graalvm.org/docs/reference-manual/aot-compilation/

**Comment by Jiri-Kremser** [comment]
graal native image is currently blocked by https://github.com/oracle/graal/issues/390

**Comment by Jiri-Kremser** [comment]
the blocking issue has been fixed, so this should be theoretically doable :champagne:

**Comment by mjschmidt** [comment]
@elmiko Github was atually just acking up. I am really sorry to spam everything. Going to re-mediate it now

**Comment by Jiri-Kremser** [comment]
`sudo dnf install zlib-devel` was also necessary for the native-image build on Fedora 28. Now this is blocked by https://github.com/oracle/graal/issues/582

**Comment by Jiri-Kremser** [comment]
the issue above has been fixed, now w/ `rc13` I am hitting:

<details>log</summary>

```
Error: unsupported features in 4 methods
Detailed message:
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object java.util.concurrent.ForkJoinPool$WorkQueue
	object java.util.concurrent.ForkJoinPool$WorkQueue[]
	object java.util.concurrent.ForkJoinPool
	method java.util.concurrent.CompletableFuture.supplyAsync(Supplier)
Call path from entry point to java.util.concurrent.CompletableFuture.supplyAsync(Supplier): 
	at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1814)
	at io.radanalytics.operator.Entrypoint.runMetrics(Entrypoint.java:115)
	at io.radanalytics.operator.Entrypoint.lambda$main$1(Entrypoint.java:66)
	at io.radanalytics.operator.Entrypoint$$Lambda$297/1309234494.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at io.radanalytics.operator.Entrypoint.main(Entrypoint.java:66)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:152)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object java.util.concurrent.ForkJoinPool$WorkQueue
	object java.util.concurrent.ForkJoinPool$WorkQueue[]
	object java.util.concurrent.ForkJoinPool
	method java.util.concurrent.CompletableFuture.supplyAsync(Supplier)
Call path from entry point to java.util.concurrent.CompletableFuture.supplyAsync(Supplier): 
	at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1814)
	at io.radanalytics.operator.Entrypoint.runMetrics(Entrypoint.java:115)
	at io.radanalytics.operator.Entrypoint.lambda$main$1(Entrypoint.java:66)
	at io.radanalytics.operator.Entrypoint$$Lambda$297/1309234494.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at io.radanalytics.operator.Entrypoint.main(Entrypoint.java:66)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:152)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.fasterxml.jackson.core.json.JsonWriteContext.typeDesc(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.writeEndArray(YAMLGenerator.java:484)
Call path from entry point to com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.writeEndArray(): 
	at com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.writeEndArray(YAMLGenerator.java:483)
	at com.fasterxml.jackson.databind.ser.impl.BeanAsArraySerializer.serialize(BeanAsArraySerializer.java:172)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3631)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2998)
	at io.fabric8.kubernetes.client.utils.Serialization.asJson(Serialization.java:55)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at io.radanalytics.operator.Entrypoint.isOnOpenShift(Entrypoint.java:206)
	at io.radanalytics.operator.Entrypoint.main(Entrypoint.java:59)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:152)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.fasterxml.jackson.core.json.JsonWriteContext.typeDesc(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.writeEndObject(YAMLGenerator.java:512)
Call path from entry point to com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.writeEndObject(): 
	at com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.writeEndObject(YAMLGenerator.java:511)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:132)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3631)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2998)
	at io.fabric8.kubernetes.client.utils.Serialization.asJson(Serialization.java:55)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at io.radanalytics.operator.Entrypoint.isOnOpenShift(Entrypoint.java:206)
	at io.radanalytics.operator.Entrypoint.main(Entrypoint.java:59)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:152)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

```

</details>

**Comment by Jiri-Kremser** [comment]
adding `--allow-incomplete-classpath` removes two errors, the rest should be doable wit detecting the right classes that will be on the `--delay-class-initialization-to-runtime` [list](https://medium.com/graalvm/understanding-class-initialization-in-graalvm-native-image-generation-d765b7e4d6ed)
